### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by viri77** [viri77/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by kwakkwel** [comment]
<h2>Résumé </h2>
<p>&mdash;Always a tone of surprise. I'm the sixth in our family to go to Hogwarts. You could say I got a lot to live up to. Bill and Charlie have already left — Bill was Head Boy and Charlie was captain of Quidditch. Now Percy's a prefect. Fred and George mess around a lot, but they still get really good marks and everyone thinks they're really funny. Everyone expects me to do as well as the others, but if I do, it's no big deal, because they did it first.</p>

**Comment by viri77** [comment]
вс, 2 мая 2021 г. в 17:37, kwakkwel ***@***.***>:

**Comment by viri77** [comment]
<h1>Ron Weasley</h1>
                <div class="job">
                    <p >co-owner Weasleys' Wizard Wheezes</p>
                </div>

                <ul class="contacts">
                    <li>
                        <a class="magic" href="
https://www.facebook.com/RonaldGingerWeasley/" target="_blank">
                            <img class='custome-image' src="
https://img.icons8.com/doodle/48/000000/facebook-new.png" width="30" height=
"30" alt='Telegram'/>
                            ronweasley
                        </a>
                    </li>
                    <li>
                        <a class="magic" href="
https://www.instagram.com/ronhermione_id/" target="_blank">
                            <img class='custom-img' src="
https://img.icons8.com/doodle/48/000000/instagram-new.png" width="30" height
="30" alt='Instagram'/>
                            ronhermione_id
                        </a>
                    </li>
                    <li>
                        <a class="magic" ***@***.***"
>
                            <img class='custom-img' src="
https://img.icons8.com/doodle/48/000000/apple-mail.png" width="30" height=
"30"
                            alt='Gmail'/>
                            ***@***.***
                        </a>
                    </li>
                </ul>
            </div>

вс, 2 мая 2021 г. в 17:49, Ольга ***@***.***>:
